sonar.projectKey=sonar-monorepo-api
sonar.projectName=Sonar Monorepo - API
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
